### PR TITLE
Delete .travis.yml

### PR DESCRIPTION
**Pull request by kvashchuka**
Delete Travis CI as we do not intend to use it anymore

### CODE REVIEW

**Comment by markusdregi** [comment]
This is a very welcome change 👏 Keen on getting away from Travis! However, currently the PyPI packages are built using Travis. Hence, we need to move that logic into Github Actions also...

**Comment by kvashchuka** [comment]
Thank you, will add the workflow for that:)

**Comment by kvashchuka** [comment]
Workflow is added, but for it to work a secret with API token from PyPi needs to be added to the repo and I don't have rights to do it. Could maybe one of the maintainers (@markusdregi or @jondequinor) do it?

**Comment by markusdregi** [comment]
I've added the PyPI password for the previously used PyPI user as a GitHub secret now @kvashchuka... But to use it I would guess you need to use the same username as the ert workflow (`statoil-travis`), although I'm not entirely sure due to lack of experienced with twine...

**Comment by markusdregi** [comment]
I've now added a `PYPI_SECRET` 👍 Let us try to merge this and make a new release.

Could you add an entry in the release notes about moving replacing the Travis CI?

**Comment by markusdregi** [comment]
The release notes are written here: https://github.com/equinor/configsuite/blob/master/docs/source/release_notes.rst and new entries are added under the `dev` section under a fitting section title. The available section titles are written at the top of the document as a comment (in the raw version).

I'm suggesting something along the lines of:

> **Miscellaneous**
>  - Stop running CI on Travis and move PyPI deploy to GitHub Actions

**Comment by kvashchuka** [comment]
Yes, I just figured it out when I saw your comment:) Could you also change settings such that travis-ci is not required for merge anymore?

**Review by markusdregi — APPROVED** [review]
Looks good 👍 Thanks for your patience!

**Pull request merged**
